name = "RootFS"
grammar = "rootfs"
path_suffixes = ["rootfs"]
line_comments = ["# "]

brackets = [
  { start = "[", end = "]", close = true, newline = true },
  { start = "{", end = "}", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
]
